import { m001Initial } from './m001-initial';
import { m002TelemetryKind } from './m002-telemetry-kind';
import { m003SessionProvider } from './m003-session-provider';
import { m004TurnOverrides } from './m004-turn-overrides';
import { m005BudgetTables } from './m005-budget-tables';
import { m006Skills } from './m006-skills';
import { m007Phases } from './m007-phases';
import { m008Permissions } from './m008-permissions';
import { m009SessionWorktrees } from './m009-session-worktrees';
import { m010PermissionAuditRetry } from './m010-permission-audit-retry';
import { m011ParallelPhases } from './m011-parallel-phases';
import { m012SettingsOverrides } from './m012-settings-overrides';
import { m013BudgetExtraTokens } from './m013-budget-extra-tokens';
import { m014RenameDomain } from './m014-rename-domain';
import { m015AgentsPerChat } from './m015-agents-per-chat';
import { m016TurnEvents } from './m016-turn-events';
import { m017ContextSlotHistory } from './m017-context-slot-history';
import { m018GithubPrCache } from './m018-github-pr-cache';
import { m019TaskPermissionMode } from './m019-task-permission-mode';
import { m020DiffComments } from './m020-diff-comments';
import { m021DiffCommentLine } from './m021-diff-comment-line';
import { m022TaskAutorun } from './m022-task-autorun';
import { m023StepEffort } from './m023-step-effort';
import { m024SessionProviderSessionId } from './m024-session-provider-session-id';
import { m025TaskTitleUserEdited } from './m025-task-title-user-edited';
import { m026Notifications } from './m026-notifications';
import { m027SessionPlans } from './m027-session-plans';
import { m028DiffCommentConsumed } from './m028-diff-comment-consumed';
import { m029AgentUnread } from './m029-agent-unread';
import { m030PlanConsumptions } from './m030-plan-consumptions';
import { m031RenameSoftDeletePersist } from './m031-rename-soft-delete-persist';
import { m032SessionUserStatus } from './m032-session-user-status';
import { m033WorkspaceInitScripts } from './m033-workspace-init-scripts';
import { m034WorkspaceDisconnectedAt } from './m034-workspace-disconnected-at';
import { m035NudgeEvents } from './m035-nudge-events';
import { m036WorkspaceScripts } from './m036-workspace-scripts';
import { m037PlanDiscardedStatus } from './m037-plan-discarded-status';
import { m038WorkspaceVerbosity } from './m038-workspace-verbosity';
import { m039WorkspaceLastAccessedAt } from './m039-workspace-last-accessed-at';
import { m040OpenQuestions } from './m040-open-questions';
import { m041SessionWorkflows } from './m041-session-workflows';
import { m042OpenQuestionsCreatedBy } from './m042-open-questions-created-by';
import { m043WorkspaceIntegrations } from './m043-workspace-integrations';
import { m044SessionExternalTask } from './m044-session-external-task';
import { m045StepLibrary } from './m045-step-library';
import { m046StepRole } from './m046-step-role';
import { m047AgentParent } from './m047-agent-parent';
import { m048PlanClusters } from './m048-plan-clusters';
import { m049SessionWorkflowDiscard } from './m049-session-workflow-discard';
import { m050ProviderCredentials } from './m050-provider-credentials';
import { m051ProviderBindings } from './m051-provider-bindings';
import { m052PendingResolutions } from './m052-pending-resolutions';
import { m053ScoutFanout } from './m053-scout-fanout';
import { m054WorkflowRunInstances } from './m054-workflow-run-instances';
import { m055ResolverCommentLink } from './m055-resolver-comment-link';
import { m056CompositeWorkspaces } from './m056-composite-workspaces';
import { m057SessionEnabledProviders } from './m057-session-enabled-providers';
import { m058WorkflowGoal } from './m058-workflow-goal';
import { m059WorkflowRunGoal } from './m059-workflow-run-goal';
import { m060WorkflowTriggerMode } from './m060-workflow-trigger-mode';
import { m061DiffCommentLineRange } from './m061-diff-comment-line-range';
import { m062OpenQuestionsTurnOrdinal } from './m062-open-questions-turn-ordinal';
import { m063OpenQuestionsRecommendedAnswer } from './m063-open-questions-recommended-answer';
import { m064SentryProvider } from './m064-sentry-provider';
import { m065IntegrationGitlabProvider } from './m065-integration-gitlab-provider';

export type Migration = {
  readonly version: number;
  readonly sql: string;
};

export const migrations: ReadonlyArray<Migration> = [
  { version: 1, sql: m001Initial },
  { version: 2, sql: m002TelemetryKind },
  { version: 3, sql: m003SessionProvider },
  { version: 4, sql: m004TurnOverrides },
  { version: 5, sql: m005BudgetTables },
  { version: 6, sql: m006Skills },
  { version: 7, sql: m007Phases },
  { version: 8, sql: m008Permissions },
  { version: 9, sql: m009SessionWorktrees },
  { version: 10, sql: m010PermissionAuditRetry },
  { version: 11, sql: m011ParallelPhases },
  { version: 12, sql: m012SettingsOverrides },
  { version: 13, sql: m013BudgetExtraTokens },
  { version: 14, sql: m014RenameDomain },
  { version: 15, sql: m015AgentsPerChat },
  { version: 16, sql: m016TurnEvents },
  { version: 17, sql: m017ContextSlotHistory },
  { version: 18, sql: m018GithubPrCache },
  { version: 19, sql: m019TaskPermissionMode },
  { version: 20, sql: m020DiffComments },
  { version: 21, sql: m021DiffCommentLine },
  { version: 22, sql: m022TaskAutorun },
  { version: 23, sql: m023StepEffort },
  { version: 24, sql: m024SessionProviderSessionId },
  { version: 25, sql: m025TaskTitleUserEdited },
  { version: 26, sql: m026Notifications },
  { version: 27, sql: m027SessionPlans },
  { version: 28, sql: m028DiffCommentConsumed },
  { version: 29, sql: m029AgentUnread },
  { version: 30, sql: m030PlanConsumptions },
  { version: 31, sql: m031RenameSoftDeletePersist },
  { version: 32, sql: m032SessionUserStatus },
  { version: 33, sql: m033WorkspaceInitScripts },
  { version: 34, sql: m034WorkspaceDisconnectedAt },
  { version: 35, sql: m035NudgeEvents },
  { version: 36, sql: m036WorkspaceScripts },
  { version: 37, sql: m037PlanDiscardedStatus },
  { version: 38, sql: m038WorkspaceVerbosity },
  { version: 39, sql: m039WorkspaceLastAccessedAt },
  { version: 40, sql: m040OpenQuestions },
  { version: 41, sql: m041SessionWorkflows },
  { version: 42, sql: m042OpenQuestionsCreatedBy },
  { version: 43, sql: m043WorkspaceIntegrations },
  { version: 44, sql: m044SessionExternalTask },
  { version: 45, sql: m045StepLibrary },
  { version: 46, sql: m046StepRole },
  { version: 47, sql: m047AgentParent },
  { version: 48, sql: m048PlanClusters },
  { version: 49, sql: m049SessionWorkflowDiscard },
  { version: 50, sql: m050ProviderCredentials },
  { version: 51, sql: m051ProviderBindings },
  { version: 52, sql: m052PendingResolutions },
  { version: 53, sql: m053ScoutFanout },
  { version: 54, sql: m054WorkflowRunInstances },
  { version: 55, sql: m055ResolverCommentLink },
  { version: 56, sql: m056CompositeWorkspaces },
  { version: 57, sql: m057SessionEnabledProviders },
  { version: 58, sql: m058WorkflowGoal },
  { version: 59, sql: m059WorkflowRunGoal },
  { version: 60, sql: m060WorkflowTriggerMode },
  { version: 61, sql: m061DiffCommentLineRange },
  { version: 62, sql: m062OpenQuestionsTurnOrdinal },
  { version: 63, sql: m063OpenQuestionsRecommendedAnswer },
  { version: 64, sql: m064SentryProvider },
  { version: 65, sql: m065IntegrationGitlabProvider },
];
