import {
  WIREFRAME_ALIGNMENTS,
  WIREFRAME_BUTTON_VARIANTS,
  WIREFRAME_DIRECTIONS,
  WIREFRAME_IMAGE_RATIOS,
  WIREFRAME_INPUT_TYPES,
  WIREFRAME_JUSTIFICATIONS,
  WIREFRAME_LIMITS,
  WIREFRAME_NAVIGATION_VARIANTS,
  WIREFRAME_SCHEMA_VERSION,
  WIREFRAME_SPACINGS,
  WIREFRAME_TEXT_VARIANTS,
  WIREFRAME_THEME_COLOR_TOKENS,
  WIREFRAME_THEME_FONTS,
  WIREFRAME_THEME_RADII,
  WIREFRAME_VIEWPORTS,
} from './schema';

const EXAMPLE = {
  version: WIREFRAME_SCHEMA_VERSION,
  initialScreenId: 'inbox',
  theme: { name: 'generic', font: 'sans', radius: 'md' },
  mockState: { isFilterOpen: false },
  screens: [
    {
      id: 'inbox',
      title: 'Inbox',
      viewport: 'desktop',
      root: {
        id: 'inbox-root',
        kind: 'stack',
        direction: 'column',
        gap: 'md',
        padding: 'lg',
        children: [
          {
            id: 'inbox-nav',
            kind: 'navigation',
            variant: 'top',
            items: [
              { id: 'nav-inbox', label: 'Inbox', isActive: true },
              { id: 'nav-archive', label: 'Archive' },
            ],
          },
          { id: 'inbox-heading', kind: 'text', text: 'Inbox', variant: 'title' },
          {
            id: 'inbox-list',
            kind: 'list',
            items: [
              {
                id: 'inbox-item-1',
                title: 'Release 0.3.0 is ready',
                subtitle: '2 minutes ago',
                action: { type: 'navigate', toScreenId: 'message' },
              },
            ],
          },
          {
            id: 'inbox-filter',
            kind: 'button',
            label: 'Filters',
            variant: 'ghost',
            action: { type: 'toggle', stateKey: 'isFilterOpen' },
          },
        ],
      },
    },
    {
      id: 'message',
      title: 'Message',
      viewport: 'desktop',
      root: {
        id: 'message-root',
        kind: 'stack',
        direction: 'column',
        gap: 'sm',
        padding: 'lg',
        children: [
          { id: 'message-subject', kind: 'text', text: 'Release 0.3.0 is ready', variant: 'title' },
          { id: 'message-hero', kind: 'image', alt: 'release chart placeholder', ratio: 'wide' },
          { id: 'message-back', kind: 'button', label: 'Back to inbox', variant: 'secondary' },
        ],
      },
    },
  ],
  transitions: [{ fromNodeId: 'message-back', toScreenId: 'inbox', label: 'back to the inbox' }],
};

export const WIREFRAME_SCHEMA_BRIEF = [
  `the wireframe document is one JSON object: { "version": ${WIREFRAME_SCHEMA_VERSION}, "initialScreenId", "theme", "screens", "transitions", "mockState" }.`,
  `screens is an array of { id, title, viewport, root, note? }; viewport is one of ${WIREFRAME_VIEWPORTS.join(', ')}. at most ${WIREFRAME_LIMITS.maxScreens} screens, ${WIREFRAME_LIMITS.maxNodes} nodes in total and ${WIREFRAME_LIMITS.maxDepth} levels of nesting.`,
  'every node is { id, kind, ... } with a unique id of letters, digits, dashes or underscores starting with a letter. the kinds are closed:',
  `- stack: direction ${WIREFRAME_DIRECTIONS.join('|')}, gap ${WIREFRAME_SPACINGS.join('|')}, padding ${WIREFRAME_SPACINGS.join('|')}, align ${WIREFRAME_ALIGNMENTS.join('|')}, justify ${WIREFRAME_JUSTIFICATIONS.join('|')}, surface true|false, children`,
  `- grid: columns 1 to ${WIREFRAME_LIMITS.maxGridColumns}, gap ${WIREFRAME_SPACINGS.join('|')}, padding ${WIREFRAME_SPACINGS.join('|')}, children`,
  `- text: text, variant ${WIREFRAME_TEXT_VARIANTS.join('|')}`,
  `- button: label, variant ${WIREFRAME_BUTTON_VARIANTS.join('|')}, optional action`,
  `- input: inputType ${WIREFRAME_INPUT_TYPES.join('|')}, label, placeholder, options`,
  '- list: items [{ id, title, subtitle, action }]',
  '- table: columns [string], rows [[string]] with one cell per column',
  `- image: alt, ratio ${WIREFRAME_IMAGE_RATIOS.join('|')}. it is always a placeholder box, never a real asset`,
  `- navigation: variant ${WIREFRAME_NAVIGATION_VARIANTS.join('|')}, items [{ id, label, isActive true|false, action }]`,
  'an action is { "type": "navigate", "toScreenId": "<declared screen id>" } or { "type": "toggle", "stateKey": "<key declared in mockState>" }. nothing else is an action.',
  'transitions is an array of { fromNodeId, toScreenId, label }; toScreenId must be a declared screen and fromNodeId must be a button node, a list item or a navigation item, never any other kind. a transition is how a clickable node navigates when it carries no inline action.',
  'one node gets exactly one action. a node must not carry an inline action and a transition that disagree with it, and two transitions must not leave the same node for different screens: either of those rejects the whole document.',
  `mockState is a flat object of at most ${WIREFRAME_LIMITS.maxMockStateKeys} boolean flags, nothing else, and a toggle action may only name a key declared there.`,
  `theme is { name, font ${WIREFRAME_THEME_FONTS.join('|')}, radius ${WIREFRAME_THEME_RADII.join('|')}, colors, sources }. colors only accepts the tokens ${WIREFRAME_THEME_COLOR_TOKENS.join(', ')} with hex values like #1a1a1a. sources is a list of repository file paths you actually read. name the theme "generic" whenever you were not handed a real design profile.`,
  'every value listed above is closed: write one of the words given, never a number, a css value or a size like xs or xl.',
  'forbidden everywhere: html, css, scripts, inline handlers, external or data urls, component imports, styling strings. any of them rejects the whole document.',
  'there is no sizing, positioning or styling property on any object: a property that is not listed above is never read, so anything you put there is lost. say it in note instead.',
  'a valid example:',
  JSON.stringify(EXAMPLE, null, 2),
].join('\n');
