import {
  WIREFRAME_ALIGNMENTS,
  WIREFRAME_BADGE_TONES,
  WIREFRAME_BUTTON_VARIANTS,
  WIREFRAME_CHART_TYPES,
  WIREFRAME_DEVICES,
  WIREFRAME_DIRECTIONS,
  WIREFRAME_IMAGE_RATIOS,
  WIREFRAME_INPUT_TYPES,
  WIREFRAME_JUSTIFICATIONS,
  WIREFRAME_LIMITS,
  WIREFRAME_NAVIGATION_VARIANTS,
  WIREFRAME_SCHEMA_VERSION,
  WIREFRAME_SHEET_PLACEMENTS,
  WIREFRAME_SPACINGS,
  WIREFRAME_TEXT_VARIANTS,
  WIREFRAME_THEME_COLOR_TOKENS,
  WIREFRAME_THEME_FONTS,
  WIREFRAME_THEME_RADII,
} from './schema';

const EXAMPLE = {
  version: WIREFRAME_SCHEMA_VERSION,
  initialScreenId: 'inbox',
  device: 'desktop',
  theme: { name: 'generic', font: 'sans', radius: 'md' },
  variants: ['full', 'first-release'],
  patterns: {
    'message-row': {
      kind: 'stack',
      direction: 'row',
      justify: 'between',
      children: [
        { id: 'subject', kind: 'text', text: '{{subject}}' },
        { id: 'age', kind: 'badge', label: '{{age}}' },
      ],
    },
  },
  screens: [
    {
      id: 'inbox',
      title: 'Inbox',
      note: 'The reader lands here after sign in.',
      states: {
        empty: { hide: ['inbox-rows'], show: ['inbox-empty'] },
      },
      root: {
        id: 'inbox-root',
        kind: 'stack',
        direction: 'column',
        gap: 'md',
        padding: 'lg',
        children: [
          {
            id: 'inbox-nav',
            kind: 'tabs',
            items: [
              { id: 'tab-inbox', label: 'Inbox', isActive: true },
              { id: 'tab-archive', label: 'Archive' },
            ],
          },
          { id: 'inbox-heading', kind: 'text', text: 'Inbox', variant: 'title' },
          {
            id: 'inbox-rows',
            kind: 'card',
            children: [
              { use: 'message-row', id: 'row-1', with: { subject: 'Release is ready', age: '2m' } },
              { use: 'message-row', id: 'row-2', with: { subject: 'Batch 4471', age: '1h' } },
            ],
          },
          {
            id: 'inbox-empty',
            kind: 'text',
            text: 'Nothing new',
            hidden: true,
          },
          {
            id: 'inbox-open',
            kind: 'button',
            label: 'Open message',
            variant: 'primary',
            note: 'The only primary on this screen.',
          },
          {
            id: 'inbox-bulk',
            kind: 'button',
            label: 'Archive all',
            only: ['full'],
          },
        ],
      },
    },
    {
      id: 'message',
      title: 'Message',
      root: {
        id: 'message-root',
        kind: 'stack',
        direction: 'column',
        gap: 'sm',
        padding: 'lg',
        children: [
          { id: 'message-subject', kind: 'text', text: 'Release is ready', variant: 'title' },
          { id: 'message-trend', kind: 'chart', label: 'Weekly releases', chartType: 'line' },
          { id: 'message-back', kind: 'button', label: 'Back to inbox', variant: 'secondary' },
        ],
      },
    },
  ],
  transitions: [
    { fromNodeId: 'inbox-open', toScreenId: 'message', label: 'open a message' },
    { fromNodeId: 'message-back', toScreenId: 'inbox', label: 'back to the inbox' },
  ],
};

export const WIREFRAME_SCHEMA_BRIEF = [
  `the wireframe document is one JSON object: { "version": ${WIREFRAME_SCHEMA_VERSION}, "initialScreenId", "device", "theme", "variants", "patterns", "screens", "transitions" }.`,
  `device is one of ${WIREFRAME_DEVICES.join(', ')} and sets the frame of every screen; a screen may set its own device.`,
  `screens is an array of { id, title, device?, root, note?, states? }. at most ${WIREFRAME_LIMITS.maxScreens} screens, ${WIREFRAME_LIMITS.maxNodes} nodes in total once patterns are expanded, and ${WIREFRAME_LIMITS.maxDepth} levels of nesting.`,
  `every node is { id, kind, note?, only?, hidden?, ... } with a unique id of at most ${WIREFRAME_LIMITS.maxIdLength} letters, digits, dashes or underscores starting with a letter. the kinds are closed:`,
  `- stack: direction ${WIREFRAME_DIRECTIONS.join('|')}, gap ${WIREFRAME_SPACINGS.join('|')}, padding ${WIREFRAME_SPACINGS.join('|')}, align ${WIREFRAME_ALIGNMENTS.join('|')}, justify ${WIREFRAME_JUSTIFICATIONS.join('|')}, surface true|false, children`,
  `- grid: columns 1 to ${WIREFRAME_LIMITS.maxGridColumns}, gap ${WIREFRAME_SPACINGS.join('|')}, padding ${WIREFRAME_SPACINGS.join('|')}, children`,
  `- card: title, padding ${WIREFRAME_SPACINGS.join('|')}, children. a bordered surface for a group`,
  `- sheet: title, placement ${WIREFRAME_SHEET_PLACEMENTS.join('|')}, children. a modal or panel drawn over the screen`,
  `- text: text, variant ${WIREFRAME_TEXT_VARIANTS.join('|')}`,
  `- button: label, variant ${WIREFRAME_BUTTON_VARIANTS.join('|')}, optional action`,
  `- input: inputType ${WIREFRAME_INPUT_TYPES.join('|')}, label, placeholder, options, at most ${WIREFRAME_LIMITS.maxSelectOptions} options`,
  `- toggle: label, isOn true|false`,
  `- badge: label, tone ${WIREFRAME_BADGE_TONES.join('|')}`,
  `- list: items [{ id, title, subtitle, action }], at most ${WIREFRAME_LIMITS.maxListItems} items`,
  `- table: columns [string], rows [[string]] with one cell per column, at most ${WIREFRAME_LIMITS.maxTableColumns} columns and ${WIREFRAME_LIMITS.maxTableRows} rows`,
  `- image: alt, ratio ${WIREFRAME_IMAGE_RATIOS.join('|')}. it is always a placeholder box, never a real asset`,
  `- chart: label, chartType ${WIREFRAME_CHART_TYPES.join('|')}. a labelled placeholder, never real data`,
  `- navigation: variant ${WIREFRAME_NAVIGATION_VARIANTS.join('|')}, items [{ id, label, isActive true|false, action }]`,
  `- tabs: items [{ id, label, isActive true|false, action }], at most ${WIREFRAME_LIMITS.maxTabs} tabs`,
  `patterns is an object of at most ${WIREFRAME_LIMITS.maxPatterns} named nodes you reuse: write { "use": "<pattern name>", "id": "<id>", "with": { "<key>": "<text>" } } where a node goes. every {{key}} inside the pattern becomes the text you pass in with, and the ids inside it become <use id>-<id inside the pattern>. a pattern never uses itself.`,
  `states is an object of at most ${WIREFRAME_LIMITS.maxStatesPerScreen} named states of a screen, like empty, loading or error: { "hide": [node ids], "show": [node ids], "text": { "<node id>": "<text>" }, "label"? }. a node with hidden true is shown only by a state that lists it in show. each state becomes its own page.`,
  `variants lists at most ${WIREFRAME_LIMITS.maxVariants} release cuts of the same flow, like full and first-release. a node with only: ["first-release"] exists only in the variants it lists.`,
  'a note on any node becomes a numbered marker on the page and an entry in the notes beside it: use notes for intent and rules, never for what the node already shows.',
  'an action is { "type": "navigate", "toScreenId": "<declared screen id>" } or { "type": "toggle", "stateKey": "<a state of a screen>" }; a toggle opens that state. nothing else is an action.',
  `transitions is an array of { fromNodeId, toScreenId, label }, at most ${WIREFRAME_LIMITS.maxTransitions} of them; toScreenId must be a declared screen and fromNodeId must be a button node, a list item, a navigation item or a tab, never any other kind. a transition is how a clickable node navigates when it carries no inline action.`,
  'one node gets exactly one action. a node must not carry an inline action and a transition that disagree with it, and two transitions must not leave the same node for different screens: either of those rejects the whole document.',
  `theme is { name, font ${WIREFRAME_THEME_FONTS.join('|')}, radius ${WIREFRAME_THEME_RADII.join('|')}, colors, sources }. colors only accepts the tokens ${WIREFRAME_THEME_COLOR_TOKENS.join(', ')} with hex values like #1a1a1a. sources is a list of repository file paths you actually read. name the theme "generic" whenever you were not handed a real design profile.`,
  `wherever a property lists its values separated by | above, that list is closed: write one of those words exactly, never a css value, a pixel size or a token like xs or xl. the exceptions are the fields that are not words at all: columns is an integer from 1 to ${WIREFRAME_LIMITS.maxGridColumns}, and surface, isActive, isOn and hidden are true or false.`,
  `every string you write, a title, a label, a text, a note, a placeholder or a table cell, is at most ${WIREFRAME_LIMITS.maxTextLength} characters. going over loses the tail, so keep the point at the front.`,
  'forbidden everywhere: html, css, scripts, inline handlers, external or data urls, component imports, styling strings. any of them rejects the whole document.',
  'there is no sizing, positioning or styling property on any object: a property that is not listed above is never read, so anything you put there is lost. say it in note instead.',
  'a valid example:',
  JSON.stringify(EXAMPLE, null, 2),
].join('\n');
