version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      workspace-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: '/website'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      website-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: '/apps/desktop/src-tauri'
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      cargo-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci
      include: scope
