import type { EffortLevel, OpenRouterModel } from '@goodboy/types';

const EFFORTS = [
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'max',
] satisfies ReadonlyArray<EffortLevel>;

export const OPENROUTER_CATALOG = [
  {
    key: 'sonnet-4.5',
    label: 'Claude Sonnet 4.5',
    tier: 'turn',
    contextWindow: 200_000,
    presentation: {
      family: 'claude',
      group: 'Sonnet',
      version: '4.5',
      order: 70,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-sonnet-4.5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'opus-4.8',
    label: 'Claude Opus 4.8',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '4.8',
      order: 80,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-opus-4.8',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'gpt-5.4',
    label: 'GPT-5.4',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.4',
      order: 60,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.4',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    tier: 'turn',
    contextWindow: 1_048_576,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.1 Pro',
      order: 54,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/google/gemini-3.1-pro-preview',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'DeepSeek',
      version: 'V4 Pro',
      order: 12,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/deepseek/deepseek-v4-pro',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'kimi-k2',
    label: 'Kimi K2',
    tier: 'cheap',
    contextWindow: 131_072,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K2',
      order: 30,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/moonshotai/kimi-k2',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'glm-5',
    label: 'GLM-5',
    tier: 'cheap',
    contextWindow: 204_800,
    presentation: {
      family: 'other',
      group: 'GLM',
      version: '5',
      order: 20,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/z-ai/glm-5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'grok-4.7',
    label: 'Grok 4.7',
    tier: 'turn',
    contextWindow: 500_000,
    presentation: {
      family: 'other',
      group: 'Grok',
      version: '4.7',
      order: 43,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/x-ai/grok-4.7',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'opus-5.5',
    label: 'Claude Opus 5.5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '5.5',
      order: 82,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-opus-5.5',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'opus-5',
    label: 'Claude Opus 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '5',
      order: 81,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-opus-5',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'fable-5.1',
    label: 'Claude Fable 5.1',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Fable',
      version: '5.1',
      order: 74,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-fable-5.1',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'fable-5',
    label: 'Claude Fable 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Fable',
      version: '5',
      order: 73,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-fable-5',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'sonnet-5',
    label: 'Claude Sonnet 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Sonnet',
      version: '5',
      order: 72,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-sonnet-5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'sonnet-4.6',
    label: 'Claude Sonnet 4.6',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Sonnet',
      version: '4.6',
      order: 71,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-sonnet-4.6',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'haiku-4.5',
    label: 'Claude Haiku 4.5',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'claude',
      group: 'Haiku',
      version: '4.5',
      order: 66,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-haiku-4.5',
    efforts: EFFORTS,
    defaultEffort: 'low',
  },
  {
    key: 'gpt-6-astra',
    label: 'GPT-6 Astra',
    tier: 'turn',
    contextWindow: 1_050_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '6 Astra',
      order: 65,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-6-astra',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'gpt-5.6-sol',
    label: 'GPT-5.6 Sol',
    tier: 'turn',
    contextWindow: 1_050_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6 Sol',
      order: 64,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.6-sol',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gpt-5.6-terra',
    label: 'GPT-5.6 Terra',
    tier: 'turn',
    contextWindow: 1_050_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6 Terra',
      order: 63,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.6-terra',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gpt-5.6-luna',
    label: 'GPT-5.6 Luna',
    tier: 'cheap',
    contextWindow: 1_050_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6 Luna',
      order: 62,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.6-luna',
    efforts: EFFORTS,
    defaultEffort: 'low',
  },
  {
    key: 'gpt-5.5',
    label: 'GPT-5.5',
    tier: 'turn',
    contextWindow: 1_050_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.5',
      order: 61,
      costTier: 'expensive',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gpt-5.3-codex',
    label: 'GPT-5.3 Codex',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'Codex',
      version: '5.3',
      order: 55,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.3-codex',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.8-flash',
    label: 'Gemini 3.8 Flash',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.8 Flash',
      order: 53,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/google/gemini-3.8-flash',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.7-flash',
    label: 'Gemini 3.7 Flash',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.7 Flash',
      order: 52,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/google/gemini-3.7-flash',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.6-flash',
    label: 'Gemini 3.6 Flash',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.6 Flash',
      order: 51,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/google/gemini-3.6-flash',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.5-flash',
    label: 'Gemini 3.5 Flash',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.5 Flash',
      order: 50,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/google/gemini-3.5-flash',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'deepseek-v4.1-flash',
    label: 'DeepSeek V4.1 Flash',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'DeepSeek',
      version: 'V4.1 Flash',
      order: 11,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/deepseek/deepseek-v4.1-flash',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'DeepSeek',
      version: 'V4 Flash',
      order: 10,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/deepseek/deepseek-v4-flash',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'kimi-k3',
    label: 'Kimi K3',
    tier: 'turn',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K3',
      order: 34,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/moonshotai/kimi-k3',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'kimi-k2.7-code',
    label: 'Kimi K2.7 Code',
    tier: 'cheap',
    contextWindow: 262_144,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K2.7 Code',
      order: 33,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/moonshotai/kimi-k2.7-code',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'kimi-k2.6',
    label: 'Kimi K2.6',
    tier: 'cheap',
    contextWindow: 262_144,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K2.6',
      order: 32,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/moonshotai/kimi-k2.6',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'kimi-k2.5',
    label: 'Kimi K2.5',
    tier: 'cheap',
    contextWindow: 262_144,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K2.5',
      order: 31,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/moonshotai/kimi-k2.5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'glm-5.3',
    label: 'GLM-5.3',
    tier: 'cheap',
    contextWindow: 1_310_720,
    presentation: {
      family: 'other',
      group: 'GLM',
      version: '5.3',
      order: 23,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/z-ai/glm-5.3',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'glm-5.2',
    label: 'GLM-5.2',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'GLM',
      version: '5.2',
      order: 22,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/z-ai/glm-5.2',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'glm-5.1',
    label: 'GLM-5.1',
    tier: 'cheap',
    contextWindow: 204_800,
    presentation: {
      family: 'other',
      group: 'GLM',
      version: '5.1',
      order: 21,
      costTier: 'cheap',
    },
    provider: 'openrouter',
    cliId: 'openrouter/z-ai/glm-5.1',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'grok-4.6',
    label: 'Grok 4.6',
    tier: 'turn',
    contextWindow: 500_000,
    presentation: {
      family: 'other',
      group: 'Grok',
      version: '4.6',
      order: 42,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/x-ai/grok-4.6',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'grok-4.5',
    label: 'Grok 4.5',
    tier: 'turn',
    contextWindow: 500_000,
    presentation: {
      family: 'other',
      group: 'Grok',
      version: '4.5',
      order: 41,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/x-ai/grok-4.5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'grok-4.3',
    label: 'Grok 4.3',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'other',
      group: 'Grok',
      version: '4.3',
      order: 40,
      costTier: 'mid',
    },
    provider: 'openrouter',
    cliId: 'openrouter/x-ai/grok-4.3',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
] satisfies ReadonlyArray<OpenRouterModel>;
