import type { EffortLevel, OpenRouterModel } from '@goodboy/types';

const EFFORTS = [
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'max',
] satisfies ReadonlyArray<EffortLevel>;

export const OPENROUTER_CATALOG = [
  {
    key: 'sonnet-4.5',
    label: 'Claude Sonnet 4.5',
    tier: 'turn',
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-sonnet-4.5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'opus-4.8',
    label: 'Claude Opus 4.8',
    tier: 'turn',
    provider: 'openrouter',
    cliId: 'openrouter/anthropic/claude-opus-4.8',
    efforts: EFFORTS,
    defaultEffort: 'high',
  },
  {
    key: 'gpt-5.4',
    label: 'GPT-5.4',
    tier: 'turn',
    provider: 'openrouter',
    cliId: 'openrouter/openai/gpt-5.4',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    tier: 'turn',
    provider: 'openrouter',
    cliId: 'openrouter/google/gemini-3.1-pro',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'deepseek-v4',
    label: 'DeepSeek V4',
    tier: 'cheap',
    provider: 'openrouter',
    cliId: 'openrouter/deepseek/deepseek-v4',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'kimi-k2',
    label: 'Kimi K2',
    tier: 'turn',
    provider: 'openrouter',
    cliId: 'openrouter/moonshotai/kimi-k2',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'glm-5',
    label: 'GLM-5',
    tier: 'cheap',
    provider: 'openrouter',
    cliId: 'openrouter/z-ai/glm-5',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'grok-4',
    label: 'Grok 4',
    tier: 'turn',
    provider: 'openrouter',
    cliId: 'openrouter/x-ai/grok-4',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
] satisfies ReadonlyArray<OpenRouterModel>;
