import type { ModelTier } from '@goodboy/types';

export const OPENROUTER_MODELS: ReadonlyArray<ModelTier> = [
  {
    id: 'openrouter/anthropic/claude-sonnet-4.5',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'claude',
    subfamily: 'sonnet',
    label: 'Claude Sonnet 4.5',
    variantLabel: '4.5',
    costTier: 'mid',
    weight: 14,
    effort: null,
  },
  {
    id: 'openrouter/anthropic/claude-opus-4.8',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'opus',
    label: 'Claude Opus 4.8',
    variantLabel: '4.8',
    costTier: 'expensive',
    weight: 80,
    effort: null,
  },
  {
    id: 'openrouter/openai/gpt-5.4',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'gpt',
    subfamily: 'gpt-5',
    label: 'GPT-5.4',
    variantLabel: '5.4',
    costTier: 'mid',
    weight: 22,
    effort: null,
  },
  {
    id: 'openrouter/google/gemini-3.1-pro',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gemini',
    subfamily: 'pro',
    label: 'Gemini 3.1 Pro',
    variantLabel: '3.1 Pro',
    costTier: 'expensive',
    weight: 30,
    effort: null,
  },
  {
    id: 'openrouter/deepseek/deepseek-v4',
    tier: 'cheap',
    contextWindow: 128_000,
    family: 'other',
    subfamily: 'deepseek',
    label: 'DeepSeek V4',
    variantLabel: 'V4',
    costTier: 'cheap',
    weight: 8,
    effort: null,
  },
  {
    id: 'openrouter/moonshotai/kimi-k2',
    tier: 'turn',
    contextWindow: 128_000,
    family: 'other',
    subfamily: 'kimi',
    label: 'Kimi K2',
    variantLabel: 'K2',
    costTier: 'mid',
    weight: 13,
    effort: null,
  },
  {
    id: 'openrouter/z-ai/glm-5',
    tier: 'cheap',
    contextWindow: 128_000,
    family: 'other',
    subfamily: 'glm',
    label: 'GLM-5',
    variantLabel: '5',
    costTier: 'cheap',
    weight: 7,
    effort: null,
  },
  {
    id: 'openrouter/x-ai/grok-4',
    tier: 'turn',
    contextWindow: 128_000,
    family: 'other',
    subfamily: 'grok',
    label: 'Grok 4',
    variantLabel: '4',
    costTier: 'expensive',
    weight: 24,
    effort: null,
  },
];
