type Params = Record<string, never>;

export const createInitialSessionViewState = ({}: Params) => ({
  selectedAgentId: {},
  scriptsLensScope: null,
  sessionViewPrefs: {},
  activeLens: {},
  focusedArtifactId: {},
  artifactFilter: {},
  artifactConversationAgentId: {},
  artifactCreation: {},
  focusedGithubIssueNumber: {},
  focusedExternalTask: {},
  agentPane: {},
  sessionStudio: {},
  workflowExpand: {},
  focusedWorkflowRunId: {},
  diffFocus: {},
  diffMountPath: {},
  diffPage: {},
  branchTab: {},
  branchThreadId: {},
  terminalMountPath: {},
  resolveQueueView: {},
  resolveItemDrafts: {},
  sessionCreations: {},
  revealedActivityRows: {},
  sessionGroupExpanded: {},
});
