import type { CodexModel, EffortLevel } from '@goodboy/types';

const FULL_EFFORTS = ['low', 'medium', 'high', 'xhigh', 'max'] satisfies ReadonlyArray<EffortLevel>;
const STANDARD_EFFORTS = ['low', 'medium', 'high', 'xhigh'] satisfies ReadonlyArray<EffortLevel>;

export const CODEX_CATALOG = [
  {
    key: 'gpt-5.6-sol',
    label: 'GPT-5.6 Sol',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6 Sol',
      order: 24,
      costTier: 'expensive',
    },
    provider: 'codex',
    variants: [{ id: 'default', label: 'Default', cliId: 'gpt-5.6-sol' }],
    efforts: FULL_EFFORTS,
    defaultEffort: 'low',
  },
  {
    key: 'gpt-5.6-terra',
    label: 'GPT-5.6 Terra',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6 Terra',
      order: 23,
      costTier: 'mid',
    },
    provider: 'codex',
    variants: [{ id: 'default', label: 'Default', cliId: 'gpt-5.6-terra' }],
    efforts: FULL_EFFORTS,
    defaultEffort: 'low',
  },
  {
    key: 'gpt-5.6-luna',
    label: 'GPT-5.6 Luna',
    tier: 'cheap',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6 Luna',
      order: 22,
      costTier: 'cheap',
    },
    provider: 'codex',
    variants: [{ id: 'default', label: 'Default', cliId: 'gpt-5.6-luna' }],
    efforts: FULL_EFFORTS,
    defaultEffort: 'low',
  },
  {
    key: 'gpt-6',
    label: 'Astra',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '6',
      order: 25,
      costTier: 'expensive',
    },
    provider: 'codex',
    variants: [{ id: 'astra', label: 'Astra', cliId: 'gpt-6-astra' }],
    efforts: FULL_EFFORTS,
    defaultEffort: 'low',
  },
  {
    key: 'gpt-5.5',
    label: 'GPT-5.5',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.5',
      order: 21,
      costTier: 'expensive',
    },
    provider: 'codex',
    variants: [{ id: 'default', label: 'Default', cliId: 'gpt-5.5' }],
    efforts: STANDARD_EFFORTS,
    defaultEffort: 'medium',
  },
] satisfies ReadonlyArray<CodexModel>;
