import type { EffortLevel, OpencodeModel } from '@goodboy/types';

const EFFORTS = [
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'max',
] satisfies ReadonlyArray<EffortLevel>;

export const OPENCODE_CATALOG = [
  {
    key: 'big-pickle',
    label: 'Big Pickle',
    tier: 'turn',
    contextWindow: 200_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'Big Pickle',
      order: 40,
      costTier: 'mid',
    },
    provider: 'opencode',
    cliId: 'opencode/big-pickle',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'minimax-m2.5',
    label: 'MiniMax M2.5',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'MiniMax M2.5',
      order: 10,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/minimax-m2.5-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'nemotron-3-super',
    label: 'Nemotron 3 Super',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'Nemotron 3 Super',
      order: 20,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/nemotron-3-super-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'ring-2.6-1t',
    label: 'Ring 2.6 1T',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'Ring 2.6 1T',
      order: 30,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/ring-2.6-1t-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
] satisfies ReadonlyArray<OpencodeModel>;
