import type { EffortLevel, OpencodeModel } from '@goodboy/types';

const EFFORTS = [
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'max',
] satisfies ReadonlyArray<EffortLevel>;

export const OPENCODE_CATALOG = [
  {
    key: 'big-pickle',
    label: 'Big Pickle',
    tier: 'turn',
    contextWindow: 200_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'Big Pickle',
      order: 40,
      costTier: 'mid',
    },
    provider: 'opencode',
    cliId: 'opencode/big-pickle',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'mimo-v2.5',
    label: 'MiMo V2.5',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'MiMo V2.5',
      order: 10,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/mimo-v2.5-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'nemotron-3-ultra',
    label: 'Nemotron 3 Ultra',
    tier: 'cheap',
    contextWindow: 1_000_000,
    presentation: {
      family: 'other',
      group: null,
      version: 'Nemotron 3 Ultra',
      order: 15,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/nemotron-3-ultra-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'muse-spark-1.2',
    label: 'Muse Spark 1.2',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: null,
      version: 'Muse Spark 1.2',
      order: 20,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/muse-spark-1.2-contributor-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'nemotron-3.5-lightning',
    label: 'Nemotron 3.5 Lightning',
    tier: 'cheap',
    contextWindow: 262_144,
    presentation: {
      family: 'other',
      group: null,
      version: 'Nemotron 3.5 Lightning',
      order: 25,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/nemotron-3.5-lightning-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'ling-3.0-flash-fin',
    label: 'Ling 3.0 Flash Fin',
    tier: 'cheap',
    contextWindow: 262_144,
    presentation: {
      family: 'other',
      group: null,
      version: 'Ling 3.0 Flash Fin',
      order: 30,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/ling-3.0-flash-fin-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
  {
    key: 'muse-spark-1.3',
    label: 'Muse Spark 1.3',
    tier: 'cheap',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: null,
      version: 'Muse Spark 1.3',
      order: 35,
      costTier: 'cheap',
    },
    provider: 'opencode',
    cliId: 'opencode/muse-spark-1.3-contributor-free',
    efforts: EFFORTS,
    defaultEffort: 'medium',
  },
] satisfies ReadonlyArray<OpencodeModel>;
