import type { ModelTier } from '@goodboy/types';

export const OPENCODE_MODELS: ReadonlyArray<ModelTier> = [
  {
    id: 'opencode/big-pickle',
    tier: 'turn',
    contextWindow: 128_000,
    family: 'other',
    subfamily: null,
    label: 'Big Pickle',
    variantLabel: 'Big Pickle',
    costTier: 'cheap',
    weight: 8,
    effort: null,
  },
  {
    id: 'opencode/deepseek-v4-flash-free',
    tier: 'cheap',
    contextWindow: 128_000,
    family: 'other',
    subfamily: null,
    label: 'DeepSeek V4 Flash Free',
    variantLabel: 'V4 Flash Free',
    costTier: 'cheap',
    weight: 6,
    effort: null,
  },
  {
    id: 'opencode/minimax-m3-free',
    tier: 'cheap',
    contextWindow: 128_000,
    family: 'other',
    subfamily: null,
    label: 'MiniMax M3 Free',
    variantLabel: 'M3 Free',
    costTier: 'cheap',
    weight: 5,
    effort: null,
  },
  {
    id: 'opencode/nemotron-3-super-free',
    tier: 'cheap',
    contextWindow: 128_000,
    family: 'other',
    subfamily: null,
    label: 'Nemotron 3 Super Free',
    variantLabel: '3 Super Free',
    costTier: 'cheap',
    weight: 4,
    effort: null,
  },
];
