import type { ModelTier } from '@goodboy/types';

export const OPENCODE_DEFAULT_MODEL = 'auto';

export const OPENCODE_MODELS: ReadonlyArray<ModelTier> = [
  {
    id: 'auto',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'opencode',
    subfamily: null,
    label: 'Auto',
    variantLabel: 'auto',
    costTier: 'cheap',
    weight: 10,
    effort: null,
  },
  {
    id: 'claude-sonnet-4-5',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'claude',
    subfamily: 'sonnet',
    label: 'Claude Sonnet 4.5',
    variantLabel: '4.5',
    costTier: 'mid',
    weight: 15,
    effort: ['low', 'medium', 'high'],
  },
  {
    id: 'gpt-4o',
    tier: 'turn',
    contextWindow: 128_000,
    family: 'gpt',
    subfamily: 'gpt-4',
    label: 'GPT-4o',
    variantLabel: '4o',
    costTier: 'mid',
    weight: 14,
    effort: null,
  },
  {
    id: 'gpt-4o-mini',
    tier: 'cheap',
    contextWindow: 128_000,
    family: 'gpt',
    subfamily: 'gpt-4',
    label: 'GPT-4o Mini',
    variantLabel: '4o mini',
    costTier: 'cheap',
    weight: 6,
    effort: null,
  },
  {
    id: 'gemini-2.5-pro',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gemini',
    subfamily: 'pro',
    label: 'Gemini 2.5 Pro',
    variantLabel: '2.5 pro',
    costTier: 'mid',
    weight: 16,
    effort: ['low', 'medium', 'high'],
  },
  {
    id: 'gemini-2.5-flash',
    tier: 'cheap',
    contextWindow: 1_000_000,
    family: 'gemini',
    subfamily: 'flash',
    label: 'Gemini 2.5 Flash',
    variantLabel: '2.5 flash',
    costTier: 'cheap',
    weight: 7,
    effort: null,
  },
];
