import type { AgentRole } from '@goodboy/types';

export const NAMES = {
  needsYou: 'Needs you',
  running: 'Running',
  inReview: 'In review',
  building: 'Building',
  done: 'Done',
  whenToAsk: 'When to ask',
  replyLength: 'Reply length',
  short: 'Short',
  normal: 'Normal',
  long: 'Long',
  stop: 'Stop',
  questions: 'Questions',
  agents: 'Agents',
  runs: 'Runs',
  review: 'Review',
  artifacts: 'Artifacts',
  scripts: 'Scripts',
  terminal: 'Terminal',
  context: 'Context',
  goal: 'Goal',
  decisions: 'Decisions',
  plan: 'Plan',
  files: 'Files',
  runDefaults: 'Run defaults',
  whatsNew: "What's new",
  spendCap: 'Spend cap',
  spendCaps: 'Spend caps',
  copyContext: 'Copy context',
  contextWindow: 'Context window',
  models: 'Models',
  addPlainFolder: 'Add a plain folder',
  addExisting: 'Add existing',
  connectIntegration: 'Connect an integration',
  runOnItsOwn: 'Run on its own',
  yourJob: 'Your job',
  role: {
    scout: 'Scout',
    planner: 'Planner',
    implementer: 'Implementer',
    reviewer: 'Reviewer',
    tester: 'Tester',
    investigator: 'Debugger',
    docs: 'Docs',
    report: 'Report',
    wireframe: 'Wireframe',
    resolver: 'Resolver',
    rewriter: 'History rewriter',
    scribe: 'Scribe',
    custom: 'Generalist',
  } satisfies Record<AgentRole, string>,
} as const;

const FORMER_NAMES: Readonly<Record<string, ReadonlyArray<string>>> = {
  [NAMES.runDefaults]: ['Rules', 'Workflow rules'],
  [NAMES.runs]: ['Workflows'],
  [NAMES.whatsNew]: ['Changelog'],
  [NAMES.spendCap]: ['Spend limit', 'Default cap', 'Cap', 'Budget cap'],
  [NAMES.spendCaps]: ['Budget rules'],
  [NAMES.copyContext]: ['Copy as brief'],
  [NAMES.contextWindow]: ['Context'],
  [NAMES.models]: ['Defaults', 'Provider defaults'],
  [NAMES.addPlainFolder]: ['Link a plain folder'],
  [NAMES.addExisting]: ['Link existing'],
  [NAMES.connectIntegration]: ['Link integration', 'Link your first integration'],
  [NAMES.runOnItsOwn]: ['Autorun'],
  [NAMES.whenToAsk]: ['Autonomy'],
  [NAMES.needsYou]: ['Waiting on you', 'Waiting on your answer'],
  [NAMES.yourJob]: ['Your roles'],
};

export const formerNamesOf = (name: string): ReadonlyArray<string> => FORMER_NAMES[name] ?? [];
