import type { AgentRole } from '@goodboy/types';

export const NAMES = {
  needsYou: 'Needs you',
  running: 'Running',
  inReview: 'In review',
  building: 'Building',
  done: 'Done',
  whenToAsk: 'When to ask',
  replyLength: 'Reply length',
  short: 'Short',
  normal: 'Normal',
  long: 'Long',
  stop: 'Stop',
  questions: 'Questions',
  agents: 'Agents',
  runs: 'Runs',
  overview: 'Overview',
  branch: 'Branch',
  comments: 'Comments',
  pullRequest: 'Pull request',
  artifacts: 'Artifacts',
  scripts: 'Scripts',
  terminal: 'Terminal',
  context: 'Context',
  goal: 'Goal',
  decisions: 'Decisions',
  plan: 'Plan',
  files: 'Files',
  runDefaults: 'Run defaults',
  whatsNew: "What's new",
  spendCap: 'Spend cap',
  spendCaps: 'Spend caps',
  copyContext: 'Copy context',
  contextWindow: 'Context window',
  models: 'Models',
  addPlainFolder: 'Add a plain folder',
  addExisting: 'Add existing',
  connectIntegration: 'Connect an integration',
  runOnItsOwn: 'Run on its own',
  yourJob: 'Your job',
  markThreadResolved: 'Mark thread as resolved',
  hasASession: 'Has a session',
  guidance: 'Guidance',
  stopRun: 'Stop run',
  archiveRun: 'Archive run',
  deleteRun: 'Delete run',
  startRun: 'Start a run',
  removeFromSession: 'Remove from session',
  deleteAllData: 'Delete all data',
  retry: 'Retry',
  removeLink: 'Remove link',
  removeLinkFromSession: 'Remove link from this session',
  legacyLayout: 'Legacy layout',
  repliesAndCommits: 'Replies and commits',
  start: 'Start',
  fix: 'Fix',
  waitingForPermission: 'Waiting for your permission',
  approve: 'Approve',
  runPlan: 'Run plan',
  follow: 'Follow',
  pin: 'Pin session',
  unpin: 'Unpin session',
  notes: 'Notes',
  tasks: 'Tasks',
  notifications: 'Notifications',
  reply: 'Reply',
  resolve: 'Resolve',
  publishReply: 'Publish reply',
  retryPush: 'Retry push',
  newBranch: 'New branch',
  closeBranch: 'Close branch',
  switchBranch: 'Switch branch',
  rebaseOn: 'Rebase on',
  role: {
    scout: 'Scout',
    planner: 'Planner',
    implementer: 'Implementer',
    reviewer: 'Reviewer',
    tester: 'Tester',
    investigator: 'Debugger',
    docs: 'Docs',
    report: 'Report',
    wireframe: 'Wireframe',
    resolver: 'Resolver',
    rewriter: 'History rewriter',
    scribe: 'Scribe',
    custom: 'Generalist',
  } satisfies Record<AgentRole, string>,
} as const;

const FORMER_NAMES: Readonly<Record<string, ReadonlyArray<string>>> = {
  [NAMES.runDefaults]: ['Rules', 'Workflow rules'],
  [NAMES.runs]: ['Workflows', 'Workflow runs'],
  [NAMES.whatsNew]: ['Changelog'],
  [NAMES.spendCap]: ['Spend limit', 'Default cap', 'Cap', 'Budget cap'],
  [NAMES.spendCaps]: ['Budget rules'],
  [NAMES.copyContext]: ['Copy as brief'],
  [NAMES.contextWindow]: ['Context'],
  [NAMES.models]: ['Defaults', 'Provider defaults'],
  [NAMES.addPlainFolder]: ['Link a plain folder'],
  [NAMES.addExisting]: ['Link existing'],
  [NAMES.connectIntegration]: ['Link integration', 'Link your first integration'],
  [NAMES.runOnItsOwn]: ['Autorun'],
  [NAMES.whenToAsk]: ['Autonomy'],
  [NAMES.needsYou]: ['Waiting on you', 'Waiting on your answer'],
  [NAMES.yourJob]: ['Your roles'],
  [NAMES.markThreadResolved]: ['Resolve the thread after replying'],
  [NAMES.hasASession]: ['With a session'],
  [NAMES.guidance]: ['Standing guidance'],
  [NAMES.stopRun]: ['Stop workflow', 'Close workflow'],
  [NAMES.archiveRun]: ['Archive workflow', 'Discard workflow'],
  [NAMES.deleteRun]: ['Delete workflow run'],
  [NAMES.startRun]: ['Run workflow', 'Start a workflow', 'Attach another workflow'],
  [NAMES.removeFromSession]: ['Detach project', 'Detach'],
  [NAMES.deleteAllData]: ['Wipe local database', 'Wipe'],
  [NAMES.retry]: ['Try again'],
  [NAMES.removeLink]: ['Unlink'],
  [NAMES.removeLinkFromSession]: ['Unlink from this session'],
  [NAMES.overview]: ['Session'],
  [NAMES.comments]: ['Review'],
  [NAMES.files]: ['Diff'],
  [NAMES.repliesAndCommits]: ['Review replies'],
  [NAMES.tasks]: ['Inbox'],
  [NAMES.fix]: ['Resolve comments', 'Draft a fix'],
  [NAMES.waitingForPermission]: ['Waiting for your approval'],
  [NAMES.reply]: ['Reply yourself'],
  [NAMES.resolve]: ['Resolve without a reply'],
  [NAMES.publishReply]: ['Post reply now'],
  [NAMES.newBranch]: ['New worktree'],
  [NAMES.closeBranch]: ['Remove worktree', 'Close worktree'],
  [NAMES.rebaseOn]: ["Start from today's main"],
};

export const formerNamesOf = (name: string): ReadonlyArray<string> => FORMER_NAMES[name] ?? [];
