export { ContextEngine, type ContextEngineDeps } from './engine';
export {
  assertSlotKey,
  InvalidSlotKeyError,
  isSlotKey,
  serializeSlots,
  serializeSlotsBudgeted,
  SLOT_KEYS,
  SLOT_LABELS,
  type SlotKey,
} from './slots';
export { PREAMBLE_SLOT_TOTAL_BUDGET, SLOT_BUDGETS } from './budgets';
export {
  assessPlanReadiness,
  extractAllCommentAnalysis,
  extractAllCommentReplies,
  extractAllCommentResolved,
  extractAllCommentWontfix,
  extractHistoryReport,
  extractScribeText,
  extractClusterDone,
  extractClustersFromMarker,
  extractCommentAnalysis,
  extractCommentResolved,
  extractCommentVerdict,
  extractCommentWontfix,
  extractFanOut,
  extractFilesTouched,
  extractHandoff,
  extractMarkers,
  extractMaterializeRequests,
  extractOpenQuestionAnswer,
  extractPlanFromMarker,
  extractReviewComments,
  extractScoutDomains,
  extractScoutSplit,
  extractStepDone,
  hasBlockingQuestion,
  isOpenQuestionAnswerText,
  isReviewThreadId,
  mergeIntoSlot,
  removeFromSlot,
  stripControlMarkers,
  wrapOpenQuestionAnswers,
  type ExtractedCluster,
  type ExtractedFanOutArea,
  type ExtractedScoutArea,
  type ExtractedCommentAnalysis,
  type ExtractedCommentReply,
  type ExtractedCommentResolution,
  type ExtractedCommentVerdict,
  type CommentVerdictKind,
  type ExtractedCommentWontfix,
  type ExtractedHistoryReport,
  type ExtractedScribeText,
  type ExtractedHandoff,
  type ExtractedMaterializeRequest,
  type ExtractedPlan,
  type ExtractedReviewComment,
  type PlanReadinessInput,
  type PlanReadinessResult,
} from './extractors';
export { extractDecisionOps, type ExtractedDecisionOp } from './marker-parsing';
export {
  activeDecisionsNewestFirst,
  applyDecisionOps,
  CONSOLIDATION_OP_KINDS,
  countDecisionChanges,
  hasVisibleDecisionChange,
  isLedgerOverBudget,
  normalizeDecisionText,
  reconcileDecisionsText,
  renderDecisionsSlot,
  seedDecisionLedger,
  type ApplyDecisionOpsResult,
  type DecisionActor,
  type DecisionChange,
  type DecisionChangeCounts,
  type DecisionOp,
  type DecisionRejection,
  type DecisionRejectionReason,
} from './decisions-ledger';
export {
  applyDecisionOpsToSession,
  loadDecisionLedger,
  type AppliedDecisionOps,
} from './decisions-ledger-store';
export { extractProseQuestion } from './prose-question';
export {
  autoPopulateContext,
  type AutoPopulateInput,
  type AutoPopulateResult,
} from './auto-populate';
export {
  addQuestionsToSlot,
  removeQuestionsFromSlot,
  removeSessionQuestionsFromSlots,
} from './slot-questions';
export {
  appendDecision,
  parseDecisions,
  removeDecision,
  replaceDecision,
  serializeDecisions,
  type DecisionRow,
  type DecisionsDocument,
} from './decisions-document';
export {
  insertSummarySection,
  parseSummaryDocument,
  replaceSummarySectionBody,
  serializeSummaryDocument,
  SUMMARY_SECTION_KEYS,
  SUMMARY_SECTION_TITLES,
  type SummaryBlock,
  type SummaryDocument,
  type SummarySectionKey,
} from './summary-document';
