import type { CursorModel } from '@goodboy/types';

export const CURSOR_CATALOG = [
  {
    key: 'composer-2.5',
    label: 'Composer 2.5',
    tier: 'turn',
    contextWindow: 200_000,
    presentation: {
      family: 'composer',
      group: 'Composer',
      version: '2.5',
      order: 20,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      { effort: null, thinking: false, fast: false, slug: 'composer-2.5', maxMode: false },
      { effort: null, thinking: false, fast: true, slug: 'composer-2.5-fast', maxMode: false },
    ],
  },
  {
    key: 'auto',
    label: 'Auto',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'cursor-auto',
      group: null,
      version: 'Auto',
      order: 10,
      costTier: 'cheap',
    },
    provider: 'cursor',
    combos: [{ effort: null, thinking: false, fast: false, slug: 'auto', maxMode: false }],
  },
  {
    key: 'opus-5',
    label: 'Opus 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '5',
      order: 41,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-low',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-opus-5-thinking-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'opus-4.7',
    label: 'Opus 4.7',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '4.7',
      order: 40,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-opus-4-7-thinking-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'sonnet-4.6',
    label: 'Sonnet 4.6',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Sonnet',
      version: '4.6',
      order: 30,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'claude-4.6-sonnet-medium',
        maxMode: false,
      },
      {
        effort: 'medium',
        thinking: true,
        fast: false,
        slug: 'claude-4.6-sonnet-medium-thinking',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gpt-5.6',
    label: 'GPT-5.6',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6',
      order: 61,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gpt-5.6-sol-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gpt-5.5',
    label: 'GPT-5.5',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.5',
      order: 60,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'gpt-5.5-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gpt-5.5-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gpt-5.3-codex',
    label: 'GPT-5.3 Codex',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'Codex',
      version: '5.3',
      order: 50,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: null,
        thinking: false,
        fast: false,
        slug: 'gpt-5.3-codex',
        maxMode: false,
      },
    ],
  },
] satisfies ReadonlyArray<CursorModel>;
