import type { CursorModel } from '@goodboy/types';

export const CURSOR_CATALOG = [
  {
    key: 'composer-2.5',
    label: 'Composer 2.5',
    tier: 'turn',
    contextWindow: 200_000,
    presentation: {
      family: 'composer',
      group: 'Composer',
      version: '2.5',
      order: 20,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      { effort: null, thinking: false, fast: false, slug: 'composer-2.5', maxMode: false },
      { effort: null, thinking: false, fast: true, slug: 'composer-2.5-fast', maxMode: false },
    ],
  },
  {
    key: 'auto',
    label: 'Auto',
    tier: 'cheap',
    contextWindow: 200_000,
    presentation: {
      family: 'cursor-auto',
      group: 'Auto',
      version: 'Auto',
      order: 10,
      costTier: 'cheap',
    },
    provider: 'cursor',
    combos: [{ effort: null, thinking: false, fast: false, slug: 'auto', maxMode: false }],
  },
  {
    key: 'opus-5',
    label: 'Opus 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '5',
      order: 42,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-low',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-opus-5-thinking-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'opus-4.7',
    label: 'Opus 4.7',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '4.7',
      order: 40,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-opus-4-7-thinking-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'sonnet-4.6',
    label: 'Sonnet 4.6',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Sonnet',
      version: '4.6',
      order: 30,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'claude-4.6-sonnet-medium',
        maxMode: false,
      },
      {
        effort: 'medium',
        thinking: true,
        fast: false,
        slug: 'claude-4.6-sonnet-medium-thinking',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gpt-5.6',
    label: 'GPT-5.6 Sol',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6',
      checkpoint: 'Sol',
      order: 61,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gpt-5.6-sol-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gpt-5.5',
    label: 'GPT-5.5',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.5',
      order: 58,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'gpt-5.5-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gpt-5.5-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gpt-5.3-codex',
    label: 'GPT-5.3 Codex',
    tier: 'turn',
    contextWindow: 400_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.3',
      checkpoint: 'Codex',
      order: 50,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: null,
        thinking: false,
        fast: false,
        slug: 'gpt-5.3-codex',
        maxMode: false,
      },
    ],
  },
  {
    key: 'sonnet-5',
    label: 'Sonnet 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Sonnet',
      version: '5',
      order: 31,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'claude-sonnet-5-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: false,
        fast: false,
        slug: 'claude-sonnet-5-xhigh',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-sonnet-5-thinking-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: true,
        fast: false,
        slug: 'claude-sonnet-5-thinking-xhigh',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gpt-5.6-terra',
    label: 'GPT-5.6 Terra',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6',
      checkpoint: 'Terra',
      order: 60,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gpt-5.6-terra-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: false,
        fast: false,
        slug: 'gpt-5.6-terra-xhigh',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gpt-5.6-luna',
    label: 'GPT-5.6 Luna',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gpt',
      group: 'GPT',
      version: '5.6',
      checkpoint: 'Luna',
      order: 59,
      costTier: 'cheap',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'gpt-5.6-luna-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gpt-5.6-luna-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'grok-4.6',
    label: 'Grok 4.6',
    tier: 'turn',
    contextWindow: 500_000,
    presentation: {
      family: 'other',
      group: 'Grok',
      version: '4.6',
      order: 70,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'cursor-grok-4.6-medium',
        maxMode: false,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: true,
        slug: 'cursor-grok-4.6-medium-fast',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gemini-3.8-flash',
    label: 'Gemini 3.8 Flash',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.8',
      checkpoint: 'Flash',
      order: 78,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'gemini-3.8-flash-low',
        maxMode: false,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'gemini-3.8-flash-medium',
        maxMode: false,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gemini-3.8-flash-high',
        maxMode: false,
      },
    ],
  },
  {
    key: 'muse-spark-1.3',
    label: 'Muse Spark 1.3',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'other',
      group: 'Muse Spark',
      version: '1.3',
      order: 80,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'muse-spark-1.3-low',
        maxMode: true,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'muse-spark-1.3-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'muse-spark-1.3-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: false,
        fast: false,
        slug: 'muse-spark-1.3-xhigh',
        maxMode: true,
      },
      {
        effort: 'max',
        thinking: false,
        fast: false,
        slug: 'muse-spark-1.3-max',
        maxMode: true,
      },
    ],
  },
  {
    key: 'kimi-k3',
    label: 'Kimi K3',
    tier: 'turn',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K3',
      order: 86,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'kimi-k3-low',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'kimi-k3-high',
        maxMode: true,
      },
      {
        effort: 'max',
        thinking: false,
        fast: false,
        slug: 'kimi-k3-max',
        maxMode: true,
      },
    ],
  },
  {
    key: 'glm-5.2',
    label: 'GLM 5.2',
    tier: 'turn',
    contextWindow: 1_048_576,
    presentation: {
      family: 'other',
      group: 'GLM',
      version: '5.2',
      order: 90,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'glm-5.2-high',
        maxMode: false,
      },
      {
        effort: 'max',
        thinking: false,
        fast: false,
        slug: 'glm-5.2-max',
        maxMode: false,
      },
    ],
  },
  {
    key: 'opus-4.8',
    label: 'Opus 4.8',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '4.8',
      order: 41,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-opus-4-8-thinking-high',
        maxMode: true,
      },
    ],
  },
  {
    key: 'opus-5.5',
    label: 'Opus 5.5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Opus',
      version: '5.5',
      order: 43,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-5-low',
        maxMode: true,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-5-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-5-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-5-xhigh',
        maxMode: true,
      },
      {
        effort: 'max',
        thinking: false,
        fast: false,
        slug: 'claude-opus-5-5-max',
        maxMode: true,
      },
    ],
  },
  {
    key: 'fable-5',
    label: 'Fable 5',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Fable',
      version: '5',
      order: 44,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-thinking-low',
        maxMode: true,
      },
      {
        effort: 'medium',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-thinking-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-thinking-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-thinking-xhigh',
        maxMode: true,
      },
      {
        effort: 'max',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-thinking-max',
        maxMode: true,
      },
    ],
  },
  {
    key: 'fable-5.1',
    label: 'Fable 5.1',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'claude',
      group: 'Fable',
      version: '5.1',
      order: 45,
      costTier: 'expensive',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-1-thinking-low',
        maxMode: true,
      },
      {
        effort: 'medium',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-1-thinking-medium',
        maxMode: true,
      },
      {
        effort: 'high',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-1-thinking-high',
        maxMode: true,
      },
      {
        effort: 'xhigh',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-1-thinking-xhigh',
        maxMode: true,
      },
      {
        effort: 'max',
        thinking: true,
        fast: false,
        slug: 'claude-fable-5-1-thinking-max',
        maxMode: true,
      },
    ],
  },
  {
    key: 'grok-4.7',
    label: 'Grok 4.7',
    tier: 'turn',
    contextWindow: 500_000,
    presentation: {
      family: 'other',
      group: 'Grok',
      version: '4.7',
      order: 71,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'grok-4.7-medium',
        maxMode: true,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: true,
        slug: 'grok-4.7-medium-fast',
        maxMode: true,
      },
    ],
  },
  {
    key: 'gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.1',
      checkpoint: 'Pro',
      order: 79,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: null,
        thinking: false,
        fast: false,
        slug: 'gemini-3.1-pro',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gemini-3.7-flash',
    label: 'Gemini 3.7 Flash',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.7',
      checkpoint: 'Flash',
      order: 77,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'gemini-3.7-flash-low',
        maxMode: false,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'gemini-3.7-flash-medium',
        maxMode: false,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gemini-3.7-flash-high',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gemini-3.6-flash',
    label: 'Gemini 3.6 Flash',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.6',
      checkpoint: 'Flash',
      order: 76,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: 'low',
        thinking: false,
        fast: false,
        slug: 'gemini-3.6-flash-low',
        maxMode: false,
      },
      {
        effort: 'medium',
        thinking: false,
        fast: false,
        slug: 'gemini-3.6-flash-medium',
        maxMode: false,
      },
      {
        effort: 'high',
        thinking: false,
        fast: false,
        slug: 'gemini-3.6-flash-high',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gemini-3.5-flash',
    label: 'Gemini 3.5 Flash',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3.5',
      checkpoint: 'Flash',
      order: 75,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: null,
        thinking: false,
        fast: false,
        slug: 'gemini-3.5-flash',
        maxMode: false,
      },
    ],
  },
  {
    key: 'gemini-3-flash',
    label: 'Gemini 3 Flash',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Gemini',
      version: '3',
      checkpoint: 'Flash',
      order: 74,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: null,
        thinking: false,
        fast: false,
        slug: 'gemini-3-flash',
        maxMode: false,
      },
    ],
  },
  {
    key: 'kimi-k2.7-code',
    label: 'Kimi K2.7 Code',
    tier: 'turn',
    contextWindow: 262_144,
    presentation: {
      family: 'other',
      group: 'Kimi',
      version: 'K2.7',
      checkpoint: 'Code',
      order: 85,
      costTier: 'mid',
    },
    provider: 'cursor',
    combos: [
      {
        effort: null,
        thinking: false,
        fast: false,
        slug: 'kimi-k2.7-code',
        maxMode: true,
      },
    ],
  },
] satisfies ReadonlyArray<CursorModel>;
