import type { ModelTier } from '@goodboy/types'
import { CURSOR_CHEAP_MODEL } from './cost'

export const CURSOR_DEFAULT_MODEL = 'composer-2'

export const CURSOR_AUTO_MODEL = 'auto'

export const CURSOR_MODELS: ReadonlyArray<ModelTier> = [
  {
    id: 'composer-2',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'composer',
    subfamily: null,
    label: 'Composer 2',
    variantLabel: '2',
    costTier: 'mid',
    weight: 12,
    effort: null,
  },
  {
    id: CURSOR_CHEAP_MODEL,
    tier: 'cheap',
    contextWindow: 200_000,
    family: 'composer',
    subfamily: null,
    label: 'Composer 2 Fast',
    variantLabel: '2 Fast',
    costTier: 'cheap',
    weight: 5,
    effort: null,
  },
  {
    id: CURSOR_AUTO_MODEL,
    tier: 'cheap',
    contextWindow: 200_000,
    family: 'cursor-auto',
    subfamily: null,
    label: 'Auto',
    variantLabel: 'auto',
    costTier: 'cheap',
    weight: 4,
    effort: null,
  },
  {
    id: 'claude-opus-4-7-thinking-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'opus',
    label: 'Opus 4.7 High',
    variantLabel: '4.7 high',
    costTier: 'expensive',
    weight: 78,
    effort: null,
  },
  {
    id: 'claude-4.6-sonnet-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'sonnet',
    label: 'Sonnet 4.6 High',
    variantLabel: '4.6 high',
    costTier: 'mid',
    weight: 16,
    effort: null,
  },
  {
    id: 'claude-4.6-sonnet-medium',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'sonnet',
    label: 'Sonnet 4.6 Medium',
    variantLabel: '4.6 medium',
    costTier: 'mid',
    weight: 15,
    effort: null,
  },
  {
    id: 'gpt-5.5-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gpt',
    subfamily: 'gpt-5',
    label: 'GPT-5.5 High',
    variantLabel: '5.5 high',
    costTier: 'expensive',
    weight: 24,
    effort: null,
  },
  {
    id: 'gpt-5.5-medium',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gpt',
    subfamily: 'gpt-5',
    label: 'GPT-5.5 Medium',
    variantLabel: '5.5 medium',
    costTier: 'mid',
    weight: 23,
    effort: null,
  },
  {
    id: 'gpt-5.3-codex',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'gpt',
    subfamily: 'codex',
    label: 'GPT-5.3 Codex',
    variantLabel: '5.3 codex',
    costTier: 'mid',
    weight: 20,
    effort: null,
  },
]
