import type { ModelTier } from '@goodboy/types';
import { CURSOR_CHEAP_MODEL } from './cost';

export const CURSOR_DEFAULT_MODEL = 'composer-2.5';

export const CURSOR_AUTO_MODEL = 'auto';

export const CURSOR_MODELS: ReadonlyArray<ModelTier> = [
  {
    id: CURSOR_DEFAULT_MODEL,
    tier: 'turn',
    contextWindow: 200_000,
    family: 'composer',
    subfamily: null,
    label: 'Composer 2.5',
    variantLabel: '2.5',
    costTier: 'mid',
    weight: 12,
    effort: null,
  },
  {
    id: CURSOR_CHEAP_MODEL,
    tier: 'cheap',
    contextWindow: 200_000,
    family: 'composer',
    subfamily: null,
    label: 'Composer 2.5 Fast',
    variantLabel: '2.5 Fast',
    costTier: 'cheap',
    weight: 5,
    effort: null,
  },
  {
    id: CURSOR_AUTO_MODEL,
    tier: 'cheap',
    contextWindow: 200_000,
    family: 'cursor-auto',
    subfamily: null,
    label: 'Auto',
    variantLabel: 'auto',
    costTier: 'cheap',
    weight: 4,
    effort: null,
  },
  {
    id: 'claude-fable-5-thinking-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'fable',
    label: 'Fable 5 Thinking',
    variantLabel: '5 thinking',
    costTier: 'expensive',
    weight: 90,
    effort: null,
  },
  {
    id: 'claude-opus-5-thinking-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'opus',
    label: 'Opus 5 Thinking',
    variantLabel: '5 thinking',
    costTier: 'expensive',
    weight: 85,
    effort: null,
  },
  {
    id: 'claude-opus-4-7-thinking-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'opus',
    label: 'Opus 4.7 High',
    variantLabel: '4.7 high',
    costTier: 'expensive',
    weight: 78,
    effort: null,
  },
  {
    id: 'claude-4.6-sonnet-medium-thinking',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'sonnet',
    label: 'Sonnet 4.6 Thinking',
    variantLabel: '4.6 thinking',
    costTier: 'mid',
    weight: 16,
    effort: null,
  },
  {
    id: 'claude-4.6-sonnet-medium',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'claude',
    subfamily: 'sonnet',
    label: 'Sonnet 4.6 Medium',
    variantLabel: '4.6 medium',
    costTier: 'mid',
    weight: 15,
    effort: null,
  },
  {
    id: 'gpt-5.6-sol-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gpt',
    subfamily: 'gpt-5',
    label: 'GPT-5.6 Sol High',
    variantLabel: '5.6 sol high',
    costTier: 'expensive',
    weight: 28,
    effort: null,
  },
  {
    id: 'gpt-5.5-high',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gpt',
    subfamily: 'gpt-5',
    label: 'GPT-5.5 High',
    variantLabel: '5.5 high',
    costTier: 'expensive',
    weight: 24,
    effort: null,
  },
  {
    id: 'gpt-5.5-medium',
    tier: 'turn',
    contextWindow: 1_000_000,
    family: 'gpt',
    subfamily: 'gpt-5',
    label: 'GPT-5.5 Medium',
    variantLabel: '5.5 medium',
    costTier: 'mid',
    weight: 23,
    effort: null,
  },
  {
    id: 'gpt-5.3-codex',
    tier: 'turn',
    contextWindow: 200_000,
    family: 'gpt',
    subfamily: 'codex',
    label: 'GPT-5.3 Codex',
    variantLabel: '5.3 codex',
    costTier: 'mid',
    weight: 20,
    effort: null,
  },
];
