import type { GeminiModel } from '@goodboy/types';

export const GEMINI_CATALOG = [
  {
    key: 'gemini-3.1-pro',
    label: '3.1 Pro',
    tier: 'turn',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Pro',
      version: '3.1',
      order: 20,
      costTier: 'mid',
    },
    provider: 'gemini',
    cliId: 'gemini-3.1-pro',
    efforts: ['low', 'high'],
    defaultEffort: 'high',
  },
  {
    key: 'gemini-3.8-flash',
    label: '3.8 Flash',
    tier: 'cheap',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Flash',
      version: '3.8',
      order: 13,
      costTier: 'cheap',
    },
    provider: 'gemini',
    cliId: 'gemini-3.8-flash',
    efforts: ['low', 'medium', 'high'],
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.7-flash',
    label: '3.7 Flash',
    tier: 'cheap',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Flash',
      version: '3.7',
      order: 12,
      costTier: 'cheap',
    },
    provider: 'gemini',
    cliId: 'gemini-3.7-flash',
    efforts: ['low', 'medium', 'high'],
    defaultEffort: 'medium',
  },
  {
    key: 'gemini-3.6-flash',
    label: '3.6 Flash',
    tier: 'cheap',
    contextWindow: 1_000_000,
    presentation: {
      family: 'gemini',
      group: 'Flash',
      version: '3.6',
      order: 11,
      costTier: 'cheap',
    },
    provider: 'gemini',
    cliId: 'gemini-3.6-flash',
    efforts: ['low', 'medium', 'high'],
    defaultEffort: 'medium',
  },
] satisfies ReadonlyArray<GeminiModel>;
