import type { ModelEntry } from './types';

// Codex CLI v0.130+. Effort is set via `-c model_reasoning_effort="<level>"`
// and is independent of the model id. The context-window values below come
// from OpenAI's API docs (developers.openai.com/api/docs/models/*), not Codex'
// own clamped display value — see openai/codex#19319 for the discrepancy.
export const CODEX_MODELS: ReadonlyArray<ModelEntry> = [
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt',
    version: '5.5',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5.5',
    supportedEfforts: ['minimal', 'low', 'medium', 'high', 'extra-high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt',
    version: '5.4',
    contextWindow: 1_050_000,
    tier: 'turn',
    baseCliId: 'gpt-5.4',
    supportedEfforts: ['minimal', 'low', 'medium', 'high', 'extra-high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-mini',
    version: '5.4-mini',
    contextWindow: 400_000,
    tier: 'cheap',
    baseCliId: 'gpt-5.4-mini',
    supportedEfforts: ['minimal', 'low', 'medium', 'high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-codex',
    version: '5.3-codex',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5.3-codex',
    supportedEfforts: ['minimal', 'low', 'medium', 'high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-codex-spark',
    version: '5.3-codex-spark',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5.3-codex-spark',
    supportedEfforts: null,
    supportsThinking: false,
    supportsFast: false,
    // ChatGPT-Pro-only — most users can't run it via API auth.
    hidden: true,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-codex',
    version: '5.2-codex',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5.2-codex',
    supportedEfforts: ['minimal', 'low', 'medium', 'high', 'extra-high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt',
    version: '5.2',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5.2',
    supportedEfforts: ['minimal', 'low', 'medium', 'high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-codex-max',
    version: '5.1-codex-max',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5.1-codex-max',
    supportedEfforts: ['minimal', 'low', 'medium', 'high', 'extra-high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-codex-mini',
    version: '5.1-codex-mini',
    contextWindow: 400_000,
    tier: 'cheap',
    baseCliId: 'gpt-5.1-codex-mini',
    supportedEfforts: ['minimal', 'low', 'medium', 'high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
  {
    provider: 'codex',
    family: 'gpt',
    subfamily: 'gpt-pro',
    version: '5-pro',
    contextWindow: 400_000,
    tier: 'turn',
    baseCliId: 'gpt-5-pro',
    supportedEfforts: ['minimal', 'low', 'medium', 'high'],
    supportsThinking: false,
    supportsFast: false,
    hidden: false,
    deprecated: false,
  },
];
