import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Bell,
  Bot,
  CheckCheck,
  CirclePlay,
  CircleHelp,
  FileDiff,
  FileText,
  FolderPlus,
  FolderTree,
  GitCommit,
  HelpCircle,
  Link2,
  ListChecks,
  ListTodo,
  MessageSquare,
  MessageSquareDiff,
  MessageSquareReply,
  Plug,
  SearchX,
  Settings,
  SquareTerminal,
  Target,
  Terminal,
  TrendingUp,
  Wallet,
  Workflow,
  Wrench,
} from 'lucide-react';
import { GithubIcon, GitlabIcon, LinearIcon, SentryIcon } from './brand-icons';

export const CONCEPT_ICONS = {
  agents: Bot,
  budget: Wallet,
  commits: GitCommit,
  decisions: CheckCheck,
  diff: FileDiff,
  explore: FolderTree,
  github: GithubIcon,
  gitlab: GitlabIcon,
  goal: Target,
  guide: HelpCircle,
  impact: TrendingUp,
  integrations: Link2,
  linear: LinearIcon,
  notifications: Bell,
  plans: FileText,
  nextUp: ListTodo,
  pr: GithubIcon,
  providers: Plug,
  questions: CircleHelp,
  resolve: MessageSquareReply,
  review: MessageSquareDiff,
  search: SearchX,
  scripts: Terminal,
  sentry: SentryIcon,
  sessions: CirclePlay,
  sessionSummary: Activity,
  settings: Settings,
  skills: Wrench,
  terminal: SquareTerminal,
  checks: ListChecks,
  comments: MessageSquare,
  workflows: Workflow,
  workspace: FolderPlus,
} satisfies Record<string, LucideIcon>;
