import type { LucideIcon } from 'lucide-react';
import type { Project } from '@goodboy/types';
import type { Tone } from '@goodboy/ui';
import {
  Archive,
  ArchiveRestore,
  ArrowRight,
  Bell,
  Blocks,
  Bot,
  Brain,
  Bug,
  CheckCheck,
  CircleAlert,
  CircleDashed,
  CircleDot,
  CircleHelp,
  CirclePlay,
  CircleSlash,
  CircleCheck,
  CircleX,
  ListVideo,
  ClipboardList,
  Ellipsis,
  FileDiff,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderTree,
  Gauge,
  GitBranch,
  GitCommit,
  GitCommitVertical,
  GitPullRequest,
  Highlighter,
  History,
  Inbox,
  Layers2,
  LayoutTemplate,
  Lightbulb,
  LifeBuoy,
  Link,
  Link2,
  ListChecks,
  MessageSquare,
  MessageSquareDiff,
  MessageSquareReply,
  Network,
  NotebookText,
  PenLine,
  SearchX,
  Settings,
  SquareArrowOutUpRight,
  SquarePen,
  SquareTerminal,
  Target,
  Trash2,
  TrendingUp,
  Wallet,
  Waypoints,
  Wrench,
} from 'lucide-react';
import {
  BitbucketIcon,
  GithubIcon,
  GitlabIcon,
  JiraIcon,
  LinearIcon,
  SentryIcon,
  SlackIcon,
} from '@goodboy/ui';

export const ICON_SIZE = {
  row: 13,
  control: 14,
  hero: 18,
} as const;

export const CONCEPT_ICONS = {
  agents: Bot,
  archive: Archive,
  autorun: Gauge,
  bitbucket: BitbucketIcon,
  branch: GitBranch,
  budget: Wallet,
  chain: Link,
  changelog: History,
  commits: GitCommit,
  context: Brain,
  decisions: CheckCheck,
  delete: Trash2,
  enhance: Highlighter,
  errors: CircleAlert,
  diff: FileDiff,
  explore: FolderSearch,
  folderOpen: FolderOpen,
  github: GithubIcon,
  gitlab: GitlabIcon,
  goal: Target,
  guide: LifeBuoy,
  impact: TrendingUp,
  inbox: Inbox,
  integrations: Link2,
  issues: CircleDot,
  jira: JiraIcon,
  linear: LinearIcon,
  more: Ellipsis,
  mount: Layers2,
  nextSteps: ArrowRight,
  notifications: Bell,
  openExternal: SquareArrowOutUpRight,
  orchestrator: Network,
  plans: ClipboardList,
  pr: GitPullRequest,
  projectFolder: Folder,
  projectRepo: FolderGit2,
  providers: Blocks,
  questions: CircleHelp,
  rename: SquarePen,
  reportIssue: Bug,
  resolve: MessageSquareReply,
  restore: ArchiveRestore,
  review: MessageSquareDiff,
  runCancelled: CircleSlash,
  runDone: CircleCheck,
  runFailed: CircleX,
  runPending: CircleDashed,
  search: SearchX,
  scripts: ListVideo,
  sentry: SentryIcon,
  sessions: CirclePlay,
  sessionSummary: NotebookText,
  settings: Settings,
  skills: Wrench,
  slack: SlackIcon,
  suggestion: Lightbulb,
  terminal: SquareTerminal,
  timeline: GitCommitVertical,
  checks: ListChecks,
  comments: MessageSquare,
  workflowCustom: PenLine,
  workflowPreset: LayoutTemplate,
  workflows: Waypoints,
  workspace: FolderPlus,
  worktree: FolderTree,
} satisfies Record<string, LucideIcon>;

type Concept = keyof typeof CONCEPT_ICONS;

export const CONCEPT_TONE = {
  agents: 'primary',
  archive: 'neutral',
  autorun: 'primary',
  bitbucket: 'primary',
  branch: 'info',
  budget: 'warning',
  chain: 'accent',
  changelog: 'neutral',
  commits: 'info',
  context: 'info',
  decisions: 'success',
  delete: 'danger',
  enhance: 'primary',
  errors: 'danger',
  diff: 'info',
  explore: 'info',
  folderOpen: 'neutral',
  github: 'primary',
  gitlab: 'primary',
  goal: 'primary',
  guide: 'info',
  impact: 'success',
  inbox: 'info',
  integrations: 'info',
  issues: 'info',
  jira: 'primary',
  linear: 'primary',
  more: 'neutral',
  mount: 'info',
  nextSteps: 'neutral',
  notifications: 'warning',
  openExternal: 'neutral',
  orchestrator: 'accent',
  plans: 'draft',
  pr: 'primary',
  projectFolder: 'neutral',
  projectRepo: 'info',
  providers: 'info',
  questions: 'warning',
  rename: 'neutral',
  reportIssue: 'info',
  resolve: 'success',
  restore: 'neutral',
  review: 'primary',
  runCancelled: 'neutral',
  runDone: 'success',
  runFailed: 'danger',
  runPending: 'neutral',
  search: 'info',
  scripts: 'info',
  sentry: 'danger',
  sessions: 'primary',
  sessionSummary: 'info',
  settings: 'neutral',
  skills: 'accent',
  slack: 'primary',
  suggestion: 'info',
  terminal: 'neutral',
  timeline: 'neutral',
  checks: 'success',
  comments: 'info',
  workflowCustom: 'accent',
  workflowPreset: 'accent',
  workflows: 'accent',
  workspace: 'info',
  worktree: 'neutral',
} satisfies Record<Concept, Tone>;

type ProjectGlyphParams = {
  readonly kind: Project['kind'] | null | undefined;
};

export const projectGlyph = ({ kind }: ProjectGlyphParams): LucideIcon =>
  kind === 'repo' ? CONCEPT_ICONS.projectRepo : CONCEPT_ICONS.projectFolder;
